setwd("/Users/perdahci/Google Drive/COURSES/DataScience/Exploratory_Data_Analysis/P1/ExData_Plotting1")
data_file <- read.csv(file = "household_power_consumption.txt", sep = ";", header = TRUE, na.strings="?")
data_file$Date <- as.POSIXct(paste(strptime(data_file$Date, "%d/%m/%Y")))
data_t <- within(data_file, { timestamp=paste(Date, Time) })
ss <- subset(data_t, timestamp > strptime("31/01/2007 00:00:00", "%d/%m/%Y %H:%M:%S") & timestamp < strptime("03/02/2007 00:00:00", "%d/%m/%Y %H:%M:%S"))
png(filename = "plot3.png", width = 480, height = 480, units = "px")
with(ss, plot(strptime(timestamp,"%Y-%m-%d %H:%M:%S"), Sub_metering_1, ylab="Energy sub metering", xlab="", type="l"))
with(ss, points(strptime(timestamp,"%Y-%m-%d %H:%M:%S"), Sub_metering_2, col = "blue",type="l"))
with(ss, points(strptime(timestamp,"%Y-%m-%d %H:%M:%S"), Sub_metering_3, col = "red", type="l"))
legend("topright", col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),lwd=c(2,2,2))
dev.off()
